/**
 * Stable catalog for the boss-book Echo collection.
 *
 * This is intentionally separate from EchoDefs.ts: the old three-card system
 * stores catalog indices and owns different spell auras. Never reorder entries.
 */

export interface CollectionEchoDef {
    /** Number in the extracted ProjectEbonhold catalog supplied by the designer. */
    catalogNumber: number;
    /** Original Ebonhold Spell.dbc row, retained only for provenance. */
    sourceId: number;
    key: string;
    name: string;
    nameRu: string;
    description: string;
    descriptionRu: string;
    icon: string;
}

export const COLLECTION_ECHOES: CollectionEchoDef[] = [
    {
        catalogNumber: 70,
        sourceId: 201416,
        key: "blade-tempest",
        name: "Blade Tempest",
        nameRu: "Буря клинков",
        description: "Direct Physical damage against an enemy affected by your periodic damage has a 5% chance to create a stationary Blade Tempest at its location for 8 sec. Every 1 sec it deals 30 Physical damage plus 60% of spell power and 30% of attack power to enemies within 8 yards. Multiple tempests can overlap.",
        descriptionRu: "Прямой физический урон по врагу, находящемуся под действием вашего периодического урона, с вероятностью 5% создаёт неподвижную бурю клинков на месте цели на 8 сек. Раз в 1 сек. она наносит противникам в радиусе 8 м 30 ед. физического урона плюс 60% от силы заклинаний и 30% от силы атаки. Несколько бурь могут действовать одновременно.",
        icon: "Interface\\Icons\\warrior_talent_icon_ravager",
    },
    {
        catalogNumber: 79,
        sourceId: 201336,
        key: "broodmothers-fury",
        name: "Broodmother's Fury",
        nameRu: "Ярость праматери",
        description: "Direct damaging spells and abilities have a 30% chance to apply Searing Cinders for 8 sec. They deal 5 Fire damage plus 15% of Fire spell power and 7.5% of attack power every 1 sec and stack up to 5 times. At 5 stacks, Deep Breath consumes them and deals 50 Fire damage plus 200% of Fire spell power and 100% of attack power to enemies in front of you. Deep Breath has a 6 sec cooldown.",
        descriptionRu: "Прямые наносящие урон заклинания и способности с вероятностью 30% накладывают «Тлеющие угли» на 8 сек. Раз в 1 сек. они наносят 5 ед. урона от огня плюс 15% от силы огненных заклинаний и 7,5% от силы атаки и суммируются до 5 раз. На 5-м заряде «Глубокое дыхание» поглощает их и наносит врагам перед вами 50 ед. урона от огня плюс 200% от силы огненных заклинаний и 100% от силы атаки. Восстановление — 6 сек.",
        icon: "Interface\\Icons\\Achievement_Boss_Onyxia",
    },
    {
        catalogNumber: 87,
        sourceId: 200632,
        key: "call-of-the-lich-king",
        name: "Call of the Lich King",
        nameRu: "Зов Короля-лича",
        description: "Killing an enemy grants a Soul Fragment. At 6 fragments they are consumed to summon a visible servant with its own 30 sec duration, up to 6 servants. Every 2 sec each living servant strikes your latest target for 5 Shadowfrost damage plus 10% of spell power and 5% of attack power.",
        descriptionRu: "Убийство врага даёт фрагмент души. Накопив 6 фрагментов, вы поглощаете их и призываете видимого слугу с собственной длительностью 30 сек.; одновременно может быть до 6 слуг. Раз в 2 сек. каждый живой слуга поражает вашу последнюю цель, нанося 5 ед. тёмно-ледяного урона плюс 10% от силы заклинаний и 5% от силы атаки.",
        icon: "Interface\\Icons\\achievement_raid_torghast_kel-thuzad",
    },
    {
        catalogNumber: 93,
        sourceId: 200627,
        key: "chill-of-the-bone-wyrm",
        name: "Chill of the Bone Wyrm",
        nameRu: "Холод костяного змея",
        description: "Frost damage grants Rime. At 12 stacks, Frost Breath consumes them and deals 30 Frost damage plus 175% of Frost spell power and 87.5% of attack power to enemies in front of you. Targets become Brittle for 5 sec and take 10% more Frost damage from you. Rime cannot be gained for 4 sec after triggering.",
        descriptionRu: "Урон от магии льда даёт заряд «Изморози». Накопив 12 зарядов, вы поглощаете их и выдыхаете мороз перед собой, нанося 30 ед. урона от магии льда плюс 175% от силы ледяных заклинаний и 87,5% от силы атаки. Цели становятся хрупкими на 5 сек. и получают от вас на 10% больше урона от магии льда. После срабатывания «Изморозь» нельзя накапливать 4 сек.",
        icon: "Interface\\Icons\\Ability_Mage_ChilledToTheBone",
    },
    {
        catalogNumber: 246,
        sourceId: 200822,
        key: "frostfire-paradox",
        name: "Frostfire Paradox",
        nameRu: "Парадокс ледяного огня",
        description: "Frost damage applies Biting Cold for 6 sec, stacking up to 10 times. Direct Fire damage against a target with at least 6 stacks consumes all stacks and deals 3 Frost damage plus 15% of spell power and 7.5% of attack power per stack to the target and enemies within 8 yards.",
        descriptionRu: "Урон от магии льда накладывает «Лютый холод» на 6 сек., суммирующийся до 10 раз. Прямой урон от огня по цели минимум с 6 зарядами поглощает все заряды и наносит цели и врагам в радиусе 8 м за каждый заряд 3 ед. урона от магии льда плюс 15% от силы заклинаний и 7,5% от силы атаки.",
        icon: "Interface\\Icons\\inv_10_blacksmithing_craftedbar_frostfirealloy",
    },
    {
        catalogNumber: 247,
        sourceId: 200443,
        key: "frostguard-carapace",
        name: "Frostguard Carapace",
        nameRu: "Панцирь ледяного стража",
        description: "When incoming damage would leave you below 50% health, damage taken is reduced by 15% for 6 sec. This effect has a 45 sec cooldown.",
        descriptionRu: "Когда полученный урон должен оставить вам менее 50% здоровья, весь получаемый урон снижается на 15% на 6 сек. Время восстановления эффекта — 45 сек.",
        icon: "Interface\\Icons\\inv_10_jewelcrafting_gem3primal_frost_cut_transparent",
    },
    {
        catalogNumber: 316,
        sourceId: 200615,
        key: "mutagenic-fumes",
        name: "Mutagenic Fumes",
        nameRu: "Мутагенные испарения",
        description: "Killing an enemy creates a Poison Cloud at its corpse for 20 sec, replacing your previous cloud. Every 1 sec it deals 5 Nature damage plus 20% of Nature spell power and 10% of attack power to enemies within 10 yards. This effect has an 8 sec cooldown.",
        descriptionRu: "Убийство врага создаёт у его тела ядовитое облако на 20 сек., заменяя ваше предыдущее облако. Раз в 1 сек. оно наносит противникам в радиусе 10 м 5 ед. урона от сил природы плюс 20% от силы природных заклинаний и 10% от силы атаки. Время восстановления эффекта — 8 сек.",
        icon: "Interface\\Icons\\Ability_Rogue_DeviousPoisons",
    },
    {
        catalogNumber: 325,
        sourceId: 201312,
        key: "nether-lords-command",
        name: "Nether Lord's Command",
        nameRu: "Приказ владыки Пустоты",
        description: "Direct damaging spells and abilities have a 15% chance to open a visible stationary Nether Portal beside your latest target for 10 sec. Every 2 sec the portal itself fires for 25 Fel damage plus 125% of Fire spell power and 62.5% of attack power. Each strike has a 25% chance to deal an additional 40 Fel damage plus 200% of Fire spell power and 100% of attack power to enemies within 5 yards, then 10 plus 40% of Fire spell power and 20% of attack power every 1 sec for 4 sec. Only one portal and one flame zone can be active. While the portal is open, another proc cannot create, refresh, or relocate it. Portal cooldown: 6 sec.",
        descriptionRu: "Прямые наносящие урон заклинания и способности с вероятностью 15% открывают рядом с последней целью видимый неподвижный портал Пустоты на 10 сек. Раз в 2 сек. сам портал стреляет в неё, нанося 25 ед. урона Скверны плюс 125% от силы огненных заклинаний и 62,5% от силы атаки. Каждый удар с вероятностью 25% дополнительно наносит врагам в радиусе 5 м 40 ед. урона Скверны плюс 200% от силы огненных заклинаний и 100% от силы атаки, а затем ещё 10 ед. плюс 40% и 20% соответственно раз в 1 сек. в течение 4 сек. Одновременно действуют только один портал и одна зона пламени. Пока портал открыт, новое срабатывание не создаёт, не обновляет и не переносит его. Восстановление портала — 6 сек.",
        icon: "Interface\\Icons\\achievement_boss_argus_femaleeredar",
    },
    {
        catalogNumber: 332,
        sourceId: 201268,
        key: "overwhelming-restoration",
        name: "Overwhelming Restoration",
        nameRu: "Неудержимое восстановление",
        description: "Increases healing done by 30%, but increases the mana cost of magic spells by 500%.",
        descriptionRu: "Увеличивает эффективность исходящего исцеления на 30%, но повышает затраты маны на магические заклинания на 500%.",
        icon: "Interface\\Icons\\inv_112_restorationdruid_ancientoflore",
    },
    {
        catalogNumber: 388,
        sourceId: 200808,
        key: "sanctum-sentries",
        name: "Sanctum Sentries",
        nameRu: "Стражи святилища",
        description: "While in combat, two visible sentries accompany you. Every 2 sec each sentry marks and claws your latest damaged target for 2 Physical damage plus 2.5% of spell power and 1.25% of attack power. Their mark makes the enemy take 10% increased damage from you for 4 sec.",
        descriptionRu: "В бою вас сопровождают два видимых стража. Раз в 2 сек. каждый страж отмечает и атакует последнюю цель, которой вы нанесли урон, нанося 2 ед. физического урона плюс 2,5% от силы заклинаний и 1,25% от силы атаки. Их метка на 4 сек. увеличивает получаемый противником урон от вас на 10%.",
        icon: "Interface\\Icons\\Ability_Mount_BlackPanther",
    },
    {
        catalogNumber: 415,
        sourceId: 200752,
        key: "spellweave",
        name: "Spellweave",
        nameRu: "Сплетение чар",
        description: "A direct healing spell increases your spell damage by 10% for 4 sec. A direct damaging spell increases healing done by 10% for 4 sec.",
        descriptionRu: "Прямое исцеляющее заклинание увеличивает ваш урон от заклинаний на 10% на 4 сек. Прямое наносящее урон заклинание увеличивает эффективность исходящего исцеления на 10% на 4 сек.",
        icon: "Interface\\Icons\\ability_evoker_innatemagic5",
    },
    {
        catalogNumber: 509,
        sourceId: 200259,
        key: "twin-casting",
        name: "Twin Casting",
        nameRu: "Двойное колдовство",
        description: "Direct unit-target damaging and healing spells from standard class families have a 35% chance to be cast a second time without an additional resource cost. This can include triggered class-family spells; generic, ground-targeted and automatic-repeat spells are not duplicated.",
        descriptionRu: "Прямые атакующие и исцеляющие заклинания стандартных классовых семейств, направленные на существо, с вероятностью 35% применяются второй раз без дополнительных затрат ресурса. Это может включать сработавшие заклинания классового семейства; общие, направленные на область и автоматически повторяемые заклинания не дублируются.",
        icon: "Interface\\Icons\\ability_evoker_pupilofalexstraza",
    },
    {
        catalogNumber: 72,
        sourceId: 200224,
        key: "blighted-sky",
        name: "Blighted Sky",
        nameRu: "Чумное небо",
        description: "Shadow damage grants a Blight charge. At 5 charges, they are consumed to erupt beneath the target for 40 Shadow damage plus 80% of spell power and 40% of attack power to enemies within 8 yards, stunning them for 2 sec. Cooldown: 8 sec.",
        descriptionRu: "Урон от Тьмы даёт заряд «Скверны». На 5 зарядах они поглощаются и вызывают под целью взрыв, наносящий противникам в радиусе 8 м 40 ед. урона от Тьмы плюс 80% от силы заклинаний и 40% от силы атаки и оглушающий их на 2 сек. Восстановление — 8 сек.",
        icon: "Interface\\Icons\\inv_10_enchanting2_magicswirl_blue",
    },
    {
        catalogNumber: 78,
        sourceId: 200780,
        key: "brittle-forging",
        name: "Brittle Forging",
        nameRu: "Хрупкая ковка",
        description: "Fire damage builds Heat on the target. At 8 stacks the target becomes Brittle for 6 sec. Your next critical Fire hit consumes Brittle and shatters for 30 Fire damage plus 100% of spell power and 50% of attack power to enemies within 8 yards. The target then resists Heat for 8 sec.",
        descriptionRu: "Урон от огня накапливает на цели «Жар». На 8 зарядах цель становится хрупкой на 6 сек. Следующий критический урон от огня поглощает хрупкость и раскалывает цель, нанося противникам в радиусе 8 м 30 ед. урона от огня плюс 100% от силы заклинаний и 50% от силы атаки. После этого цель 8 сек. не получает «Жар».",
        icon: "Interface\\Icons\\inv_10_blacksmithing_craftedbar_frostfirealloy",
    },
    {
        catalogNumber: 80,
        sourceId: 200589,
        key: "broodmothers-webbing",
        name: "Broodmother's Webbing",
        nameRu: "Паутина Матери стаи",
        description: "Direct damage that would leave you below 35% health scatters webbing, dealing 30 Nature damage plus 100% of spell power and 50% of attack power to nearby enemies and stunning them for 3 sec. Cooldown: 45 sec.",
        descriptionRu: "Прямой урон, который должен оставить менее 35% здоровья, разбрасывает паутину, нанося ближайшим противникам 30 ед. урона от сил природы плюс 100% от силы заклинаний и 50% от силы атаки и оглушая их на 3 сек. Восстановление — 45 сек.",
        icon: "Interface\\Icons\\Ability_Mount_BlackPanther",
    },
    {
        catalogNumber: 91,
        sourceId: 201318,
        key: "champions-rally",
        name: "Champion's Rally",
        nameRu: "Боевой клич чемпиона",
        description: "Healing grants Rally. At 5 stacks they are consumed to heal the target for 50 plus 100% of spell power and grant Encouraging Cry for 8 sec, reducing damage taken by 15% and increasing healing received by 20%. While it lasts, 30% of your healing also restores the most injured nearby ally.",
        descriptionRu: "Исцеление даёт заряд «Сбора». На 5 зарядах они поглощаются, исцеляя цель на 50 ед. плюс 100% от силы заклинаний и накладывая «Ободряющий клич» на 8 сек.: получаемый урон снижается на 15%, а получаемое исцеление увеличивается на 20%. Пока клич активен, 30% вашего исцеления также получает самый раненый союзник поблизости.",
        icon: "Interface\\Icons\\Ability_Druid_HealingInstincts",
    },
    {
        catalogNumber: 95,
        sourceId: 200635,
        key: "cinders-of-the-sanctum",
        name: "Cinders of the Sanctum",
        nameRu: "Угли Святилища",
        description: "Fire damage grants a Cinder. At 12 stacks they are consumed to summon a stationary Fire Cyclone for 8 sec. Every 1 sec it deals 15 Fire damage plus 30% of spell power and 15% of attack power to enemies within 8 yards. Cinders cannot be gained for 6 sec after triggering.",
        descriptionRu: "Урон от огня даёт заряд «Углей». На 12 зарядах они поглощаются и призывают неподвижный огненный циклон на 8 сек. Раз в 1 сек. он наносит противникам в радиусе 8 м 15 ед. урона от огня плюс 30% от силы заклинаний и 15% от силы атаки. После срабатывания «Угли» нельзя получать 6 сек.",
        icon: "Interface\\Icons\\Achievement_Boss_Onyxia",
    },
    {
        catalogNumber: 97,
        sourceId: 200844,
        key: "constellations",
        name: "Constellations",
        nameRu: "Созвездия",
        description: "Direct critical hits have a 25% chance to call a Falling Star for 20 Arcane damage plus 50% of spell power and 25% of attack power. After 5 stars hit, a Big Bang deals 100 Arcane damage plus 250% of spell power and 125% of attack power, divided among enemies within 10 yards.",
        descriptionRu: "Прямые критические удары с вероятностью 25% призывают падающую звезду, наносящую 20 ед. урона от тайной магии плюс 50% от силы заклинаний и 25% от силы атаки. После попадания 5 звёзд происходит Большой взрыв: 100 ед. урона от тайной магии плюс 250% и 125% соответственно делятся между противниками в радиусе 10 м.",
        icon: "Interface\\Icons\\ability_titankeeper_phasing",
    },
    {
        catalogNumber: 138,
        sourceId: 200592,
        key: "curse-of-the-plaguebringer",
        name: "Curse of the Plaguebringer",
        nameRu: "Проклятие Чумотворца",
        description: "Shadow damage builds Contagion on the target. At 8 stacks it becomes an 8 sec curse dealing 15 Shadow damage plus 50% of spell power and 25% of attack power every 2 sec. Each tick jumps the curse to one nearby enemy not already affected.",
        descriptionRu: "Урон от Тьмы накапливает на цели «Заражение». На 8 зарядах оно превращается в 8-секундное проклятие, раз в 2 сек. наносящее 15 ед. урона от Тьмы плюс 50% от силы заклинаний и 25% от силы атаки. Каждый тик переносит проклятие на одного ближайшего ещё не поражённого противника.",
        icon: "Interface\\Icons\\Ability_Rogue_DeviousPoisons",
    },
    {
        catalogNumber: 141,
        sourceId: 201378,
        key: "dark-nucleus",
        name: "Dark Nucleus",
        nameRu: "Тёмное ядро",
        description: "Taking direct damage has a 20% chance to create a Dark Nucleus for 6 sec. It absorbs 20% of incoming damage, up to 20% of maximum health. When it expires or fills, it fires a Shadow Lance at your latest target for twice the absorbed amount. Cooldown: 20 sec.",
        descriptionRu: "Получение прямого урона с вероятностью 20% создаёт «Тёмное ядро» на 6 сек. Оно поглощает 20% входящего урона, но не более 20% максимального здоровья. При окончании или заполнении ядро выпускает в последнюю цель копьё Тьмы с уроном в двойном размере от поглощённого. Восстановление — 20 сек.",
        icon: "Interface\\Icons\\Spell_Magic_LesserInvisibilty",
    },
    {
        catalogNumber: 142,
        sourceId: 201344,
        key: "deathwhispers-barrier",
        name: "Deathwhisper's Barrier",
        nameRu: "Барьер Смертного Шёпота",
        description: "Direct damage that would leave you below 40% health grants an 8 sec barrier for 25% of maximum mana, or 12.5% of maximum health without mana. It absorbs the triggering hit first. Every 1 sec while any barrier remains, it deals 20 Shadow damage plus 40% of spell power and 20% of attack power to nearby enemies. Cooldown: 45 sec.",
        descriptionRu: "Прямой урон, который должен оставить менее 40% здоровья, накладывает барьер на 8 сек. объёмом 25% максимальной маны либо 12,5% максимального здоровья, если маны нет. Сначала он поглощает вызвавший его удар. Пока щит не исчерпан, раз в 1 сек. он наносит ближайшим противникам 20 ед. урона от Тьмы плюс 40% от силы заклинаний и 20% от силы атаки. Восстановление — 45 сек.",
        icon: "Interface\\Icons\\inv_shield_1h_earthendungeon_c_02",
    },
    {
        catalogNumber: 143,
        sourceId: 201402,
        key: "defile",
        name: "Defile",
        nameRu: "Осквернение",
        description: "Killing an enemy creates one Defile zone at its location for 10 sec. Every 1 sec it deals 20 Shadow damage plus 40% of spell power and 20% of attack power within 6 yards. Enemies killed inside extend it by 2 sec and increase radius by 1 yard and damage by 20%, up to 5 times.",
        descriptionRu: "Убийство врага создаёт в его точке одну зону «Осквернения» на 10 сек. Раз в 1 сек. она наносит в радиусе 6 м 20 ед. урона от Тьмы плюс 40% от силы заклинаний и 20% от силы атаки. Враги, погибшие внутри, продлевают её на 2 сек., увеличивают радиус на 1 м и урон на 20%, максимум 5 раз.",
        icon: "Interface\\Icons\\achievement_raid_torghast_kel-thuzad",
    },
    {
        catalogNumber: 150,
        sourceId: 201258,
        key: "demonic-awakening",
        name: "Demonic Awakening",
        nameRu: "Демоническое пробуждение",
        description: "Direct damage that would drop you below 35% health transforms you for 10 sec. Damage dealt is increased by 20%; direct damage heals you for 10% of its amount and cleaves one nearby enemy for 30%. Cooldown: 60 sec.",
        descriptionRu: "Прямой урон, который должен опустить здоровье ниже 35%, превращает вас в демона на 10 сек. Наносимый урон увеличивается на 20%; прямой урон исцеляет вас на 10% от своей величины и поражает ещё одного ближайшего противника на 30%. Восстановление — 60 сек.",
        icon: "Interface\\Icons\\inv_plate_raidwarrior_o_01helm",
    },
    {
        catalogNumber: 393,
        sourceId: 200667,
        key: "scorched-path",
        name: "Scorched Path",
        nameRu: "Обожжённый путь",
        description: "While moving in combat, you leave embers once per second. Each patch lasts 5 sec and deals 8 Fire damage plus 20% of spell power and 10% of attack power every 1 sec within 3 yards, slowing enemies by 30% for 2 sec.",
        descriptionRu: "Двигаясь в бою, раз в секунду вы оставляете угли. Каждый участок существует 5 сек. и раз в 1 сек. наносит противникам в радиусе 3 м 8 ед. урона от огня плюс 20% от силы заклинаний и 10% от силы атаки, замедляя их на 30% на 2 сек.",
        icon: "Interface\\Icons\\rogue_burstofspeed",
    },
    {
        catalogNumber: 412,
        sourceId: 201360,
        key: "slime-spray",
        name: "Slime Spray",
        nameRu: "Брызги слизи",
        description: "Direct damage has a 15% chance to infect the target for 8 sec, dealing 10 Nature damage plus 30% of spell power and 15% of attack power every 2 sec and stacking Mutated Plague. Each Plague stack lasts 8 sec and deals 4 damage plus 7.5% of spell power and 3.75% of attack power every 2 sec, up to 5 stacks. When the infection expires or the target dies, it leaves an 8 sec slime pool that damages enemies within 6 yards and adds more Plague.",
        descriptionRu: "Прямой урон с вероятностью 15% заражает цель на 8 сек., раз в 2 сек. нанося 10 ед. урона от сил природы плюс 30% от силы заклинаний и 15% от силы атаки и накапливая «Мутировавшую чуму». Каждый её заряд действует 8 сек. и раз в 2 сек. наносит 4 ед. урона плюс 7,5% от силы заклинаний и 3,75% от силы атаки; суммируется до 5 раз. Когда инфекция заканчивается или цель погибает, остаётся лужа слизи на 8 сек., наносящая урон врагам в радиусе 6 м и добавляющая новые заряды чумы.",
        icon: "Interface\\Icons\\inv_10_skinning_scales_black",
    },
    {
        catalogNumber: 413,
        sourceId: 201304,
        key: "slimebound-husk",
        name: "Slimebound Husk",
        nameRu: "Скованный слизью панцирь",
        description: "Direct damage taken grants Molten Blood, stacking to 5. At 5 stacks you shed your skin, leaving an 8 sec poison pool that deals 15 Nature damage plus 50% of spell power and 25% of attack power every 1 sec within 6 yards. You also gain 30% movement speed and 15% damage reduction for 6 sec.",
        descriptionRu: "Получаемый прямой урон даёт «Расплавленную кровь», суммирующуюся до 5 раз. На 5 зарядах вы сбрасываете кожу и оставляете ядовитую лужу на 8 сек., раз в 1 сек. наносящую в радиусе 6 м 15 ед. урона от сил природы плюс 50% от силы заклинаний и 25% от силы атаки. Вы также получаете 30% скорости передвижения и 15% снижения урона на 6 сек.",
        icon: "Interface\\Icons\\ability_racial_pureblood",
    },
    {
        catalogNumber: 425,
        sourceId: 200860,
        key: "static-overflow",
        name: "Static Overflow",
        nameRu: "Избыток статики",
        description: "After charging for 10 sec in combat, your next damaging spell or attack releases lightning at up to 3 additional nearby enemies for 20 Nature damage plus 40% of spell power and 20% of attack power. Consuming the charge begins the next 10 sec charge.",
        descriptionRu: "После 10 сек. зарядки в бою следующее наносящее урон заклинание или атака выпускает молнии не более чем в 3 дополнительных ближайших противников, нанося 20 ед. урона от сил природы плюс 40% от силы заклинаний и 20% от силы атаки. Расход заряда начинает следующую 10-секундную зарядку.",
        icon: "Interface\\Icons\\Spell_Magic_ManaGain",
    },
    {
        catalogNumber: 433,
        sourceId: 200804,
        key: "stone-shatter",
        name: "Stone Shatter",
        nameRu: "Каменный раскол",
        description: "The first direct hit marks an enemy with Shatter for 12 sec. If it dies while marked, it explodes for 20 Physical damage plus 50% of spell power and 25% of attack power to enemies within 8 yards.",
        descriptionRu: "Первый прямой удар отмечает врага «Расколом» на 12 сек. Если отмеченный враг погибает, он взрывается и наносит противникам в радиусе 8 м 20 ед. физического урона плюс 50% от силы заклинаний и 25% от силы атаки.",
        icon: "Interface\\Icons\\inv_ability_mountainthanewarrior_thorimsmight",
    },
    {
        catalogNumber: 466,
        sourceId: 200232,
        key: "storm-conductor",
        name: "Storm Conductor",
        nameRu: "Проводник бури",
        description: "After 5 direct damaging hits, Chain Lightning strikes the target and jumps to up to 3 nearby enemies, dealing 30 Nature damage plus 75% of spell power and 37.5% of attack power to each.",
        descriptionRu: "После 5 прямых наносящих урон попаданий цель поражает цепная молния, перескакивающая ещё на 3 ближайших врагов и наносящая каждому 30 ед. урона от сил природы плюс 75% от силы заклинаний и 37,5% от силы атаки.",
        icon: "Interface\\Icons\\Spell_Arcane_ManaTap",
    },
    {
        catalogNumber: 507,
        sourceId: 201428,
        key: "twilight-combustion",
        name: "Twilight Combustion",
        nameRu: "Сумеречное горение",
        description: "Fire damage applies Burning Combustion for 6 sec, dealing 5 Fire damage plus 10% of spell power and 5% of attack power every 1 sec; Shadow damage applies an equivalent Soul Consumption effect. When both meet on one target they are consumed to create an 8 sec Twilight Rift beneath it, dealing 20 Shadowflame damage plus 60% of spell power and 30% of attack power every 1 sec within 6 yards.",
        descriptionRu: "Урон от огня накладывает «Огненное горение» на 6 сек., раз в 1 сек. наносящее 5 ед. урона от огня плюс 10% от силы заклинаний и 5% от силы атаки; урон от Тьмы накладывает такое же «Поглощение души». Встретившись на одной цели, эффекты поглощаются и создают под ней сумеречный разлом на 8 сек., раз в 1 сек. наносящий в радиусе 6 м 20 ед. урона пламени Тьмы плюс 60% от силы заклинаний и 30% от силы атаки.",
        icon: "Interface\\Icons\\achievement_boss_argus_femaleeredar",
    },
    {
        catalogNumber: 508,
        sourceId: 201324,
        key: "twilight-equilibrium",
        name: "Twilight Equilibrium",
        nameRu: "Сумеречное равновесие",
        description: "You begin in Light Essence. Holy, Fire and Nature damage builds up to 8 Light charges; Shadow, Frost or Arcane damage consumes them in an area Shadow burst per charge and switches you to Dark Essence. Dark Essence reverses the schools and releases a Holy burst before switching back.",
        descriptionRu: "Вы начинаете с «Сущности Света». Урон Светом, огнём и силами природы накапливает до 8 светлых зарядов; урон Тьмой, льдом или тайной магией поглощает их, создаёт по одному заряду урона от Тьмы по области и переключает вас на «Тёмную сущность». В тёмной сущности школы меняются местами, а перед возвратом к Свету происходит взрыв Света.",
        icon: "Interface\\Icons\\Spell_Holy_ArcaneIntellect",
    },
    {
        catalogNumber: 545,
        sourceId: 200585,
        key: "widows-venom",
        name: "Widow's Venom",
        nameRu: "Яд вдовы",
        description: "Nature damage grants Toxicity. At 10 stacks they are consumed to volley every enemy within 10 yards for 40 Nature damage plus 100% of spell power and 50% of attack power, then poison them for 6 sec for 10 plus 25% of spell power and 12.5% of attack power every 1 sec. Cooldown: 8 sec.",
        descriptionRu: "Урон от сил природы даёт «Ядовитость». На 10 зарядах она поглощается и выпускает залп во всех врагов в радиусе 10 м: 40 ед. урона от сил природы плюс 100% от силы заклинаний и 50% от силы атаки, а затем ещё 10 ед. плюс 25% и 12,5% соответственно раз в 1 сек. в течение 6 сек. Восстановление — 8 сек.",
        icon: "Interface\\Icons\\Ability_Rogue_DeviousPoisons",
    },
];
