/**
 * Pure runtime/addon contract for player-operated resource generators.
 *
 * GameObject and custom wood item IDs are generated by TSWoW, so consumers
 * resolve entryTag/output.tag with UTAG after `build data` instead of freezing
 * generated numeric IDs in source.
 */

export const RESOURCE_GENERATOR_KEY_START = 200;
export const RESOURCE_GENERATOR_KEY_END = 251;
export const RESOURCE_GENERATOR_COST = 40;
export const RESOURCE_GENERATOR_PERIOD_S = 30 * 60;
export const RESOURCE_GENERATOR_DOUBLE_READY_S = 60 * 60;
export const RESOURCE_GENERATOR_CAST_MS = 3000;

export const TAG_RESOURCE_GENERATOR_PLACE_SPELL = "spell/resource-generator-place";
export const TAG_RESOURCE_GENERATOR_PLACE_ITEM = "item/resource-generator-place";
export const TAG_RESOURCE_GENERATOR_GATHER_SPELL = "spell/resource-generator-gather";
export const TAG_RESOURCE_GENERATOR_READY_EFFECT = "go/resource-generator-ready-effect";

export interface ResourceGeneratorYield {
    count: number;
    weight: number;
}

/** One weighted roll per harvest; waiting an hour doubles the result, never beyond x2. */
export const RESOURCE_GENERATOR_YIELDS: ResourceGeneratorYield[] = [
    { count: 3, weight: 60 },
    { count: 5, weight: 30 },
    { count: 10, weight: 10 },
];

export type ResourceGeneratorCategory = "ore" | "herb" | "stone" | "wood" | "fish" | "junk";
export type ResourceGeneratorSkill = "mining" | "herbalism" | "woodcutting" | "fishing";
export type ResourceGeneratorOutputPool = "" | "junk";

export interface ResourceGeneratorItemRef {
    /** Stock item entry; zero when tag contains a generated custom item. */
    entry: number;
    /** Unique TSWoW tag; empty for stock items. */
    tag: string;
    nameEn: string;
    nameRu: string;
}

export interface ResourceGeneratorCost {
    item: ResourceGeneratorItemRef;
    count: number;
}

export interface ResourceGeneratorDef {
    key: number;
    id: string;
    nameEn: string;
    nameRu: string;
    category: ResourceGeneratorCategory;
    /** Numeric gameobject_template entry, filled by hydrateResourceGeneratorCatalog in livescripts. */
    entry: number;
    /** Resolve this unique tag to the generated gameobject_template entry. */
    entryTag: string;
    output: ResourceGeneratorItemRef;
    /** Non-empty only for random salvage pools. */
    outputPool: ResourceGeneratorOutputPool;
    cost: ResourceGeneratorCost;
    skill: ResourceGeneratorSkill;
    requiredSkill: number;
    castMs: number;
    periodS: number;
    doubleReadyS: number;
    /** Stock visual donor used only by datascripts. */
    sourceEntry: number;
    /** Overrides the donor display when non-zero (custom trees). */
    display: number;
    /** Overrides the donor scale when non-zero (custom trees). */
    size: number;
    nativeFishing: boolean;
}

interface ResourceGeneratorSeed {
    id: string;
    category: ResourceGeneratorCategory;
    outputEntry: number;
    outputTag: string;
    outputNameEn: string;
    outputNameRu: string;
    skill: ResourceGeneratorSkill;
    requiredSkill: number;
    sourceEntry: number;
    display?: number;
    size?: number;
    outputPool?: ResourceGeneratorOutputPool;
    costEntry?: number;
    costNameEn?: string;
    costNameRu?: string;
}

const SEEDS: ResourceGeneratorSeed[] = [
    /* Mining: exact ore types used by the base smelter. */
    { id: "copper-ore", category: "ore", outputEntry: 2770, outputTag: "", outputNameEn: "Copper Ore", outputNameRu: "Медная руда", skill: "mining", requiredSkill: 1, sourceEntry: 1731 },
    { id: "tin-ore", category: "ore", outputEntry: 2771, outputTag: "", outputNameEn: "Tin Ore", outputNameRu: "Оловянная руда", skill: "mining", requiredSkill: 65, sourceEntry: 1732 },
    { id: "silver-ore", category: "ore", outputEntry: 2775, outputTag: "", outputNameEn: "Silver Ore", outputNameRu: "Серебряная руда", skill: "mining", requiredSkill: 75, sourceEntry: 1733 },
    { id: "iron-ore", category: "ore", outputEntry: 2772, outputTag: "", outputNameEn: "Iron Ore", outputNameRu: "Железная руда", skill: "mining", requiredSkill: 125, sourceEntry: 1735 },
    { id: "gold-ore", category: "ore", outputEntry: 2776, outputTag: "", outputNameEn: "Gold Ore", outputNameRu: "Золотая руда", skill: "mining", requiredSkill: 155, sourceEntry: 1734 },
    { id: "mithril-ore", category: "ore", outputEntry: 3858, outputTag: "", outputNameEn: "Mithril Ore", outputNameRu: "Мифриловая руда", skill: "mining", requiredSkill: 175, sourceEntry: 2040 },
    { id: "truesilver-ore", category: "ore", outputEntry: 7911, outputTag: "", outputNameEn: "Truesilver Ore", outputNameRu: "Руда истинного серебра", skill: "mining", requiredSkill: 230, sourceEntry: 2047 },
    { id: "thorium-ore", category: "ore", outputEntry: 10620, outputTag: "", outputNameEn: "Thorium Ore", outputNameRu: "Ториевая руда", skill: "mining", requiredSkill: 250, sourceEntry: 324 },
    { id: "fel-iron-ore", category: "ore", outputEntry: 23424, outputTag: "", outputNameEn: "Fel Iron Ore", outputNameRu: "Руда осквернённого железа", skill: "mining", requiredSkill: 275, sourceEntry: 181555 },
    { id: "adamantite-ore", category: "ore", outputEntry: 23425, outputTag: "", outputNameEn: "Adamantite Ore", outputNameRu: "Адамантитовая руда", skill: "mining", requiredSkill: 325, sourceEntry: 181556 },
    { id: "cobalt-ore", category: "ore", outputEntry: 36909, outputTag: "", outputNameEn: "Cobalt Ore", outputNameRu: "Кобальтовая руда", skill: "mining", requiredSkill: 350, sourceEntry: 189978 },
    { id: "saronite-ore", category: "ore", outputEntry: 36912, outputTag: "", outputNameEn: "Saronite Ore", outputNameRu: "Саронитовая руда", skill: "mining", requiredSkill: 400, sourceEntry: 189980 },
    { id: "titanium-ore", category: "ore", outputEntry: 36910, outputTag: "", outputNameEn: "Titanium Ore", outputNameRu: "Титановая руда", skill: "mining", requiredSkill: 450, sourceEntry: 191133 },

    /* Herbalism: exact herbs used by the base alchemy catalog. */
    { id: "peacebloom", category: "herb", outputEntry: 2447, outputTag: "", outputNameEn: "Peacebloom", outputNameRu: "Мироцвет", skill: "herbalism", requiredSkill: 1, sourceEntry: 1618 },
    { id: "silverleaf", category: "herb", outputEntry: 765, outputTag: "", outputNameEn: "Silverleaf", outputNameRu: "Сребролист", skill: "herbalism", requiredSkill: 1, sourceEntry: 1617 },
    { id: "mageroyal", category: "herb", outputEntry: 785, outputTag: "", outputNameEn: "Mageroyal", outputNameRu: "Магороза", skill: "herbalism", requiredSkill: 50, sourceEntry: 1620 },
    { id: "briarthorn", category: "herb", outputEntry: 2450, outputTag: "", outputNameEn: "Briarthorn", outputNameRu: "Остротерн", skill: "herbalism", requiredSkill: 70, sourceEntry: 1621 },
    { id: "kingsblood", category: "herb", outputEntry: 3356, outputTag: "", outputNameEn: "Kingsblood", outputNameRu: "Королевская кровь", skill: "herbalism", requiredSkill: 125, sourceEntry: 1624 },
    { id: "stranglekelp", category: "herb", outputEntry: 3820, outputTag: "", outputNameEn: "Stranglekelp", outputNameRu: "Удавник", skill: "herbalism", requiredSkill: 85, sourceEntry: 2045 },
    { id: "goldthorn", category: "herb", outputEntry: 3821, outputTag: "", outputNameEn: "Goldthorn", outputNameRu: "Златошип", skill: "herbalism", requiredSkill: 170, sourceEntry: 2046 },
    { id: "khadgars-whisker", category: "herb", outputEntry: 3358, outputTag: "", outputNameEn: "Khadgar's Whisker", outputNameRu: "Ус Кадгара", skill: "herbalism", requiredSkill: 185, sourceEntry: 2043 },
    { id: "sungrass", category: "herb", outputEntry: 8838, outputTag: "", outputNameEn: "Sungrass", outputNameRu: "Солнечник", skill: "herbalism", requiredSkill: 230, sourceEntry: 142142 },
    { id: "dreamfoil", category: "herb", outputEntry: 13463, outputTag: "", outputNameEn: "Dreamfoil", outputNameRu: "Снолист", skill: "herbalism", requiredSkill: 270, sourceEntry: 176584 },
    { id: "felweed", category: "herb", outputEntry: 22785, outputTag: "", outputNameEn: "Felweed", outputNameRu: "Сквернопля", skill: "herbalism", requiredSkill: 300, sourceEntry: 181270 },
    { id: "goldclover", category: "herb", outputEntry: 36901, outputTag: "", outputNameEn: "Goldclover", outputNameRu: "Златоклевер", skill: "herbalism", requiredSkill: 350, sourceEntry: 189973 },
    { id: "icethorn", category: "herb", outputEntry: 36906, outputTag: "", outputNameEn: "Icethorn", outputNameRu: "Ледошип", skill: "herbalism", requiredSkill: 435, sourceEntry: 190172 },

    /* Mining by-products. Visuals deliberately follow their matching ore tier. */
    { id: "rough-stone", category: "stone", outputEntry: 2835, outputTag: "", outputNameEn: "Rough Stone", outputNameRu: "Грубый камень", skill: "mining", requiredSkill: 1, sourceEntry: 1731 },
    { id: "coarse-stone", category: "stone", outputEntry: 2836, outputTag: "", outputNameEn: "Coarse Stone", outputNameRu: "Необработанный камень", skill: "mining", requiredSkill: 65, sourceEntry: 1732 },
    { id: "heavy-stone", category: "stone", outputEntry: 2838, outputTag: "", outputNameEn: "Heavy Stone", outputNameRu: "Тяжёлый камень", skill: "mining", requiredSkill: 125, sourceEntry: 1735 },
    { id: "solid-stone", category: "stone", outputEntry: 7912, outputTag: "", outputNameEn: "Solid Stone", outputNameRu: "Твёрдый камень", skill: "mining", requiredSkill: 175, sourceEntry: 2040 },
    { id: "dense-stone", category: "stone", outputEntry: 12365, outputTag: "", outputNameEn: "Dense Stone", outputNameRu: "Массивный камень", skill: "mining", requiredSkill: 250, sourceEntry: 324 },

    /* Custom woodcutting outputs are resolved by their existing unique item tags. */
    { id: "pine-log", category: "wood", outputEntry: 0, outputTag: "item/wood-tier-1", outputNameEn: "Pine Log", outputNameRu: "Сосновое бревно", skill: "woodcutting", requiredSkill: 1, sourceEntry: 0, display: 7459, size: 0.23 },
    { id: "oak-log", category: "wood", outputEntry: 0, outputTag: "item/wood-tier-2", outputNameEn: "Oak Log", outputNameRu: "Дубовое бревно", skill: "woodcutting", requiredSkill: 75, sourceEntry: 0, display: 967, size: 0.5 },
    { id: "ash-log", category: "wood", outputEntry: 0, outputTag: "item/wood-tier-3", outputNameEn: "Ash Log", outputNameRu: "Ясеневое бревно", skill: "woodcutting", requiredSkill: 150, sourceEntry: 0, display: 702, size: 0.45 },
    { id: "ironwood-log", category: "wood", outputEntry: 0, outputTag: "item/wood-tier-4", outputNameEn: "Ironwood Log", outputNameRu: "Бревно железного дерева", skill: "woodcutting", requiredSkill: 225, sourceEntry: 0, display: 7321, size: 0.043 },
    { id: "terokkar-log", category: "wood", outputEntry: 0, outputTag: "item/wood-tier-5", outputNameEn: "Terokkar Log", outputNameRu: "Тероккарское бревно", skill: "woodcutting", requiredSkill: 300, sourceEntry: 0, display: 7288, size: 0.2 },
    { id: "frostwood-log", category: "wood", outputEntry: 0, outputTag: "item/wood-tier-6", outputNameEn: "Frostwood Log", outputNameRu: "Морозное бревно", skill: "woodcutting", requiredSkill: 375, sourceEntry: 0, display: 7801, size: 1.3 },

    /* Current raw-fish inputs accepted by the base cooking station. */
    { id: "brilliant-smallfish", category: "fish", outputEntry: 6291, outputTag: "", outputNameEn: "Raw Brilliant Smallfish", outputNameRu: "Сырая блестящая рыбка", skill: "fishing", requiredSkill: 1, sourceEntry: 180656 },
    { id: "slitherskin-mackerel", category: "fish", outputEntry: 6303, outputTag: "", outputNameEn: "Raw Slitherskin Mackerel", outputNameRu: "Сырая скользкокожая скумбрия", skill: "fishing", requiredSkill: 1, sourceEntry: 180656 },
    { id: "longjaw-mud-snapper", category: "fish", outputEntry: 6289, outputTag: "", outputNameEn: "Raw Longjaw Mud Snapper", outputNameRu: "Сырой илистый луциан", skill: "fishing", requiredSkill: 50, sourceEntry: 180656 },
    { id: "loch-frenzy", category: "fish", outputEntry: 6317, outputTag: "", outputNameEn: "Raw Loch Frenzy", outputNameRu: "Сырая озёрная бешенка", skill: "fishing", requiredSkill: 50, sourceEntry: 180656 },
    { id: "rainbow-fin-albacore", category: "fish", outputEntry: 6361, outputTag: "", outputNameEn: "Raw Rainbow Fin Albacore", outputNameRu: "Сырой радужный тунец", skill: "fishing", requiredSkill: 75, sourceEntry: 180656 },
    { id: "rockscale-cod", category: "fish", outputEntry: 6362, outputTag: "", outputNameEn: "Raw Rockscale Cod", outputNameRu: "Сырая каменношкурая треска", skill: "fishing", requiredSkill: 125, sourceEntry: 180656 },
    { id: "spotted-yellowtail", category: "fish", outputEntry: 4603, outputTag: "", outputNameEn: "Raw Spotted Yellowtail", outputNameRu: "Сырой пятнистый желтохвост", skill: "fishing", requiredSkill: 175, sourceEntry: 180656 },
    { id: "raw-redgill", category: "fish", outputEntry: 13758, outputTag: "", outputNameEn: "Raw Redgill", outputNameRu: "Сырой краснобородочник", skill: "fishing", requiredSkill: 225, sourceEntry: 180656 },
    { id: "mithril-head-trout", category: "fish", outputEntry: 8365, outputTag: "", outputNameEn: "Raw Mithril Head Trout", outputNameRu: "Сырая мифрилоголовая форель", skill: "fishing", requiredSkill: 225, sourceEntry: 180656 },

    /* Wreckage pools use tier fish as reproducible 40-item anchor costs. */
    { id: "salvage-puddle", category: "junk", outputEntry: 0, outputTag: "", outputNameEn: "Floating Debris", outputNameRu: "Плавающий мусор", outputPool: "junk", costEntry: 6291, costNameEn: "Raw Brilliant Smallfish", costNameRu: "Сырая блестящая рыбка", skill: "fishing", requiredSkill: 1, sourceEntry: 180655 },
    { id: "schooner-wreckage", category: "junk", outputEntry: 0, outputTag: "", outputNameEn: "Schooner Wreckage", outputNameRu: "Разбитая шхуна", outputPool: "junk", costEntry: 6361, costNameEn: "Raw Rainbow Fin Albacore", costNameRu: "Сырой радужный тунец", skill: "fishing", requiredSkill: 75, sourceEntry: 180662 },
    { id: "waterlogged-wreckage", category: "junk", outputEntry: 0, outputTag: "", outputNameEn: "Waterlogged Wreckage", outputNameRu: "Плавающие обломки", outputPool: "junk", costEntry: 6362, costNameEn: "Raw Rockscale Cod", costNameRu: "Сырая каменношкурая треска", skill: "fishing", requiredSkill: 150, sourceEntry: 180685 },
    { id: "floating-wreckage", category: "junk", outputEntry: 0, outputTag: "", outputNameEn: "Floating Wreckage", outputNameRu: "Обломки в воде", outputPool: "junk", costEntry: 13758, costNameEn: "Raw Redgill", costNameRu: "Сырая краснобородка", skill: "fishing", requiredSkill: 225, sourceEntry: 180751 },
    { id: "bloodsail-wreckage", category: "junk", outputEntry: 0, outputTag: "", outputNameEn: "Bloodsail Wreckage", outputNameRu: "Обломки кораблекрушения Кровавого Паруса", outputPool: "junk", costEntry: 8365, costNameEn: "Raw Mithril Head Trout", costNameRu: "Сырая мифрилоголовая форель", skill: "fishing", requiredSkill: 225, sourceEntry: 180901 },
    { id: "steam-pump-flotsam", category: "junk", outputEntry: 0, outputTag: "", outputNameEn: "Steam Pump Flotsam", outputNameRu: "Обломки парового насоса", outputPool: "junk", costEntry: 27422, costNameEn: "Barbed Gill Trout", costNameRu: "Колючеусая форель", skill: "fishing", requiredSkill: 325, sourceEntry: 182952 },
];

function item(entry: number, tag: string, nameEn: string, nameRu: string): ResourceGeneratorItemRef {
    return { entry: entry, tag: tag, nameEn: nameEn, nameRu: nameRu };
}

function generatorName(category: ResourceGeneratorCategory, resource: string, ru: boolean): string {
    if (category == "fish") return ru ? `Лунка: ${resource}` : `Fishing Hole: ${resource}`;
    if (category == "junk") return resource;
    return ru ? `Генератор: ${resource}` : `${resource} Generator`;
}

export function resourceGeneratorEntryTag(id: string): string {
    return `go/resource-generator-${id}`;
}

export const RESOURCE_GENERATORS: ResourceGeneratorDef[] = SEEDS.map((seed, index) => {
    const output = item(seed.outputEntry, seed.outputTag, seed.outputNameEn, seed.outputNameRu);
    const cost = seed.costEntry === undefined
        ? item(output.entry, output.tag, output.nameEn, output.nameRu)
        : item(seed.costEntry, "", seed.costNameEn || "", seed.costNameRu || "");
    return {
        key: RESOURCE_GENERATOR_KEY_START + index,
        id: seed.id,
        nameEn: generatorName(seed.category, seed.outputNameEn, false),
        nameRu: generatorName(seed.category, seed.outputNameRu, true),
        category: seed.category,
        entry: 0,
        entryTag: resourceGeneratorEntryTag(seed.id),
        output: output,
        outputPool: seed.outputPool || "",
        cost: { item: cost, count: RESOURCE_GENERATOR_COST },
        skill: seed.skill,
        requiredSkill: seed.requiredSkill,
        castMs: RESOURCE_GENERATOR_CAST_MS,
        periodS: RESOURCE_GENERATOR_PERIOD_S,
        doubleReadyS: RESOURCE_GENERATOR_DOUBLE_READY_S,
        sourceEntry: seed.sourceEntry,
        display: seed.display || 0,
        size: seed.size || 0,
        nativeFishing: seed.category == "fish" || seed.category == "junk",
    };
});

/** Existing saved mine/garden rows remain valid and behave as the first exact generator of their profession. */
export const LEGACY_RESOURCE_GENERATOR_ALIASES = [
    { legacyKey: 75, generatorKey: 200 }, // generic mine -> copper ore
    { legacyKey: 76, generatorKey: 213 }, // generic herb garden -> peacebloom
];

/**
 * Livescripts pass literal UTAG results here once at startup. Literal calls stay
 * outside the shared file because TSWoW resolves tags while compiling scripts.
 */
export function hydrateResourceGeneratorCatalog(entries: number[], woodItems: number[]): void {
    hydrateResourceGeneratorEntries(entries);
    hydrateResourceGeneratorWoodItems(woodItems);
}

export function hydrateResourceGeneratorEntries(entries: number[]): void {
    if (entries.length != RESOURCE_GENERATORS.length) {
        throw new Error(`expected ${RESOURCE_GENERATORS.length} resource generator entries, got ${entries.length}`);
    }
    for (let i = 0; i < RESOURCE_GENERATORS.length; i++) {
        RESOURCE_GENERATORS[i].entry = entries[i];
    }
}

/** Addon-safe hydration: BaseState already carries these six custom item IDs. */
export function hydrateResourceGeneratorWoodItems(woodItems: number[]): void {
    if (woodItems.length != 6) throw new Error(`expected 6 wood item entries, got ${woodItems.length}`);
    let woodIndex = 0;
    for (let i = 0; i < RESOURCE_GENERATORS.length; i++) {
        const def = RESOURCE_GENERATORS[i];
        if (def.output.tag != "") {
            def.output.entry = woodItems[woodIndex++];
            def.cost.item.entry = def.output.entry;
        }
    }
}

export function resourceGeneratorByKey(key: number): ResourceGeneratorDef | undefined {
    for (let i = 0; i < LEGACY_RESOURCE_GENERATOR_ALIASES.length; i++) {
        if (LEGACY_RESOURCE_GENERATOR_ALIASES[i].legacyKey == key) {
            key = LEGACY_RESOURCE_GENERATOR_ALIASES[i].generatorKey;
            break;
        }
    }
    const index = key - RESOURCE_GENERATOR_KEY_START;
    return index >= 0 && index < RESOURCE_GENERATORS.length ? RESOURCE_GENERATORS[index] : undefined;
}

/** Small build-time/self-check: catches key drift and accidental non-matching 40-resource costs. */
export function validateResourceGeneratorCatalog(): string[] {
    const errors: string[] = [];
    if (RESOURCE_GENERATORS.length != RESOURCE_GENERATOR_KEY_END - RESOURCE_GENERATOR_KEY_START + 1) {
        errors.push("resource generator count does not match reserved key range");
    }
    for (let i = 0; i < RESOURCE_GENERATORS.length; i++) {
        const def = RESOURCE_GENERATORS[i];
        if (def.key != RESOURCE_GENERATOR_KEY_START + i) errors.push(`non-contiguous generator key ${def.key}`);
        if (def.cost.count != RESOURCE_GENERATOR_COST) errors.push(`invalid construction cost for ${def.id}`);
        if (def.outputPool == "") {
            if (def.output.entry != def.cost.item.entry || def.output.tag != def.cost.item.tag) {
                errors.push(`construction resource differs from output for ${def.id}`);
            }
        } else if (def.cost.item.entry <= 0) {
            errors.push(`random generator ${def.id} has no anchor cost item`);
        }
    }
    return errors;
}
